/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nishantbank;
import javax.swing.*;
/*
 *
 * @author DELL
 */
public class Transfe_Money extends javax.swing.JFrame {

    /**
     * Creates new form Transfe_Money
     */
    public Transfe_Money() {
        initComponents();
        ButtonGroup bg=new ButtonGroup(); 
        bg.add(jCheckBox1);
        bg.add(jCheckBox2);
        bg.add(jCheckBox3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        withdraw = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("ENTER MONEY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(102, 255, 102));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox1.setForeground(java.awt.Color.red);
        jCheckBox1.setText("WITHDRAW_MONEY");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        withdraw.setBackground(new java.awt.Color(102, 255, 102));
        withdraw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        withdraw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, java.awt.Color.red));
        jPanel1.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 112, 250, 40));

        jCheckBox2.setBackground(new java.awt.Color(102, 255, 102));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox2.setForeground(java.awt.Color.red);
        jCheckBox2.setText("DEPOSIT_MONEY");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("ENTER MONEY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        deposit.setBackground(new java.awt.Color(102, 255, 102));
        deposit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deposit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, java.awt.Color.red));
        jPanel1.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 255, 260, 40));

        jCheckBox3.setBackground(new java.awt.Color(102, 255, 102));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox3.setForeground(java.awt.Color.red);
        jCheckBox3.setText("CHECK BALANCE");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.red);
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 371, 260, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            String s=withdraw.getText();
            try
            {
            double w=Double.parseDouble(s);
             loginPage.ob.deposit(w);
            }
            catch(NumberFormatException e)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Invalid Balance");
            }
        }
        else if(jCheckBox2.isSelected())
        {
            String s=deposit.getText();
            try
            {
            double w=Double.parseDouble(s);
            loginPage.ob.withdraw(w);
            }
            catch(NumberFormatException e)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Invalid Balance");
            }
        }
        else
        {
  javax.swing.JOptionPane.showMessageDialog(null, "Balance="+ loginPage.ob.getBalance());
                
        }
        withdraw.setText("");
        deposit.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfe_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfe_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfe_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfe_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfe_Money().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deposit;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField withdraw;
    // End of variables declaration//GEN-END:variables
}
